Uptime Kuma setup in docker compose and added the new docker compose setup for the Ci/Cd file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,6 +43,7 @@ jobs:
 
   docker:
     runs-on: ubuntu-latest
+    needs: [frontend, backend]
     steps:
       - uses: actions/checkout@v4
       - uses: docker/setup-buildx-action@v3
@@ -51,3 +52,24 @@ jobs:
           context: backend-python
           push: false
           tags: factorypulse-api:${{ github.sha }}
+      
+      - name Start full stack with docker compose
+        run: docker-compose up -d --build
+
+      - name: Test Nginx Reverse Proxy and Backend Health
+        run: |
+          for  i in {1..15}: do
+            if curl -s -f http://localhost/api/health | grep -q "ok"; then
+              echo "Nginx and backend are up and running"
+              exit 0
+            fi
+            sleep 2
+          done
+          echo "Nginx or backend failed to start"
+          docker compose logs
+          exit 1
+          
+      - name Stop containers
+        if: always()
+        run: docker-compose down
+    
